# Force push code to GitLab for deployment

name: Mirror

# Only mirror if build succeeds
on:
   workflow_run:
      workflows: ["Build"]
      types:
        - completed

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0    # ← fetch full history + all tags
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitlab.sccs.swarthmore.edu/sccs/tickflow.git'
          GIT_USERNAME: mirrorbot
          GIT_PASSWORD: ${{ secrets.MIRRORBOT_GIT_PASSWORD }}
          GIT_PUSH_ARGS: "--tags"